# Generated by Django 5.0.6 on 2024-10-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='detallesolicitud',
            name='estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='marca',
            name='estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='stand',
            name='estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.IntegerField(default=2),
        ),
    ]
