# Generated by Django 5.0.6 on 2024-10-07 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_detallepedido_estado_detallesolicitud_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='default_image.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='ubicacion',
            field=models.CharField(default='almacén', max_length=255),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_pedido', to='gestion.pedido'),
        ),
        migrations.AlterField(
            model_name='detallesolicitud',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_solicitud', to='gestion.solicitud'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon', models.TextField()),
                ('descripcion', models.TextField()),
                ('fecha_devolucion', models.DateField()),
                ('estado', models.IntegerField(default=1)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('estado', models.IntegerField(default=1)),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_devolucion', to='gestion.devolucion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_producto', to='gestion.devolucion')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoStand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('estado', models.IntegerField(default=1)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.producto')),
                ('stand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.stand')),
            ],
        ),
    ]
