# Generated by Django 5.0.6 on 2024-10-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_movimiento_delete_movimientos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='talla',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
