# Generated by Django 5.0.6 on 2024-10-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_producto_estado_producto_imagen_producto_stock_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='ruc',
            field=models.CharField(default='00000000000', max_length=11),
        ),
    ]
