# Generated by Django 5.0.6 on 2024-10-30 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_alter_movimiento_monto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='valor_unitario',
        ),
    ]
