# Generated by Django 5.0.6 on 2024-10-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='estado',
            field=models.IntegerField(default=1),
        ),
    ]
