# Generated by Django 5.0.6 on 2024-10-02 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_customuser_estado'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
